### ISSUE TITLE
Static resources with content type 'application/zip' not handled correctly

### ISSUE THREAD

**Issue by florian-interaktiv** [forcedotcom/lwc-dev-server-feedback#14]
**Describe the bug**
When trying to fetch a file inside a zipped static resource file, the startup script only copies the zip file into the `.localdevserver/public/assets/` folder.
File references inside the app are correct, but requesting them ends in a `500 server error`:

```
Error: Route must be specified
    at Object.assert (/Users/Florian/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/utils/assert.js:6:15)
    at generateHTML (/Users/Florian/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/document/document-service.js:48:14)
    at /Users/Florian/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/server/template-middleware.js:34:32
    at Layer.handle [as handle_request] (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/layer.js:95:5)
    at /Users/Florian/.local/share/sfdx/node_modules/express/lib/router/index.js:281:22
    at param (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/Florian/.local/share/sfdx/node_modules/express/lib/router/index.js:365:14)
```
When you now create a new folder with the same name as the static resource, then copy all included (unzip) into this folder, it works.

This might be a more detailed version of #4 

**To Reproduce**

1. create project with a new lwc
2. create zipped static resource with a js file inside
3. create a component that loads the file via `lightning/platformResourceLoader`
4. start lwc dev server
5. Open the component page
6. observe network tab of developer console
7. 500 pops out for javascript file you tried to load from static resource

**Expected behavior**
The file inside the zipped resource should be loaded properly

**Screenshots**
![image](https://user-images.githubusercontent.com/25959438/66322145-f4194480-e921-11e9-94b1-7f6501439b46.png)
![image](https://user-images.githubusercontent.com/25959438/66322196-06937e00-e922-11e9-9540-799af7d4b779.png)

**Desktop:**
 - MacOS `10.14.6`
 - Browser chrome `Version 77.0.3865.90`
 - `@salesforce/lwc-dev-server 1.0.4`
`sfdx-cli/7.25.3-16d54c01ee darwin-x64 node-v10.15.3`

**Comment by KrisGraySFDC** [comment]
Good point, we should support reading from zipped resources.

**Comment by KrisGraySFDC** [comment]
Filed work item: W-6745909

**Comment by edmondo1984** [comment]
Is there a workaround? This is really annoying, because it is related to another issue here https://github.com/forcedotcom/lwc-dev-server-feedback/issues/41 can you please re-open it by the way?
