### ISSUE TITLE
Can't start local server

### ISSUE THREAD

**Issue by mikhailivanov** [forcedotcom/lwc-dev-server-feedback#141]
**Describe the bug**

I am using the command `sfdx force:lightning:lwc:start -u TMS/develop`.

There is a log:

`Use of this plugin is subject to the Salesforce.com Program Agreement.                                     
By installing this plugin, you agree to the Salesforce.com Program Agreement<https://trailblazer.me/terms> 
and acknowledge the Salesforce Privacy Policy<https://www.salesforce.com/company/privacy.jsp>.             

Starting LWC Local Development.                
        Username: test-y9paklqolmqe@example.com
        Api Version: 49.0                      

Custom labels 'C:\Work\DX\TMS_DX\sfdx-source\TMS\main\default\labels\CustomLabels.labels-meta.xml' were not found
[HPM] Proxy created: /  -> https://innovation-power-8798-dev-ed.my.salesforce.com
[HPM] Subscribed to http-proxy events: [ 'proxyReq', 'error', 'close' ]
LWR6003: Listening on :3333
Server up on http://localhost:3333
LWR6000: Created version hash "57fe29aad4"
CLIError: timed out
    at Object.error (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9) {
  oclif: { exit: 2 },
  code: undefined
}
CLIError: timed out
    at Object.error (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9) {
  oclif: { exit: 2 },
  code: undefined
}
LWR6004: Server is shutdown
Error: timed out
    at Object.error (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\User\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9)`

**Expected behavior**
It should run the server without the unexpected shutdown.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by kaustubh-wakhare-isobar** [comment]
Getting same issue 
`Starting LWC Local Development.
        Username: test-z1pqjbmf3duy@example.com
        Api Version: 49.0

[HPM] Proxy created: /  -> https://connect-customization-3267-dev-ed.my.salesforce.com
[HPM] Subscribed to http-proxy events: [ 'proxyReq', 'error', 'close' ]
cp: no such file or directory: C:/Users/kaustubh.wakhare/OneDrive - dentsu/Documents/B2B/ToDo-Manager/force-app/main/default/staticresources/*
cp: no such file or directory: C:/Users/kaustubh.wakhare/OneDrive - dentsu/Documents/B2B/ToDo-Manager/force-app/main/default/contentassets/*
LWR6003: Listening on :3333
Server up on http://localhost:3333
LWR6000: Created version hash "d5fe1f17e8"
CLIError: timed out
    at Object.error (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9) {
  oclif: { exit: 2 },
  code: undefined
}
CLIError: timed out
    at Object.error (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9) {
  oclif: { exit: 2 },
  code: undefined
}
LWR6004: Server is shutdown
Error: timed out
    at Object.error (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\kaustubh.wakhare\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9)`
    
 **Expected behavior**
It should run the server without the unexpected shutdown.

**OS**: Windows 10
    
And updated latest sfdx version

**Comment by lxw-2000** [comment]
same question...

**Comment by lxw-2000** [comment]
CLIError: timed out
    at Object.error (C:\Users\Administrator\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\errors\index.js:28:15)
    at C:\Users\Administrator\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:25:66
    at async flush (C:\Users\Administrator\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9) {
  code: undefined
}
--------------------------------------------my solution------------------------------------
into C:\Users\Administrator\AppData\Local\sfdx\client\7.163.0-ea5a9c6\node_modules\@oclif\core\lib\cli-ux\index.js:121:9 and  
update  async flush() {
        await timeout(flush(), 10000000);
        //set timeout 10000000,the old is 10000!
    },
