### ISSUE TITLE
Untrapped error when user is not authenticated

### ISSUE THREAD

**Issue by AltiusRupert** [forcedotcom/lwc-dev-server-feedback#2]
**Describe the bug**
$ sfdx force:lightning:lwc:start
triggers an untrapped error when user is not logged into the scratch org :

**To Reproduce**
1. Go to SFDX project in terminal
2. Make sure you are not logged into any scratch org
3. run the following command :
$ sfdx force:lightning:lwc:start

4. see error in terminal
Use of this plugin is subject to the Salesforce.com Program Agreement. 
By installing this plugin, you agree to the Salesforce.com Program Agreement<https://trailblazer.me/terms> 
and acknowledge the Salesforce Privacy Policy<https://www.salesforce.com/company/privacy.jsp>.

(node:58521) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - "[{\"message\":\"Session expired or invalid\",\"errorCode\":\"INVALID_SESSION_ID\"}]"
    at new StatusCodeError (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
(node:58521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Starting LWC Local Development.
    Dev Hub Org: xxx@yyy.com
    Scratch Org: xxx@example.com - Error authenticating to your scratch org. Make sure that it is still active by running sfdx force:org:list --all.
    Api Version: 47.0
(node:58521) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - "{\"error\":\"invalid_grant\",\"error_description\":\"expired access/refresh token\"}"
    at new StatusCodeError (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/rupert/.local/share/sfdx/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/Users/rupert/.local/share/sfdx/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
(node:58521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Expected behavior**
Should just report a user friendly error message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Smartphone (please complete the following information):**

**Additional context**
SFDX version :
sfdx-cli/7.26.0-9118501918 darwin-x64 node-v10.15.3

SFDX plugins :
@salesforce/lwc-dev-server 1.0.4
├─ @oclif/plugin-help 2.2.1
└─ @oclif/plugin-update 1.3.9

mo-dx-plugin 0.2.5
sfdx-migration-automatic 1.5.0
sfdx-waw-plugin 1.5.0
shane-sfdx-plugins 4.6.1

**Comment by keirbowden** [comment]
Adding on to this - I got this exception when my default scratch org was all set up. I then executed `force:org:open`, which opened the scratch org without err. I then ran `force:lightning:lwc:start` again, and it worked fine this time.

**Comment by KrisGraySFDC** [comment]
Thanks! This is simply promises that aren't registering a catch. We've filed a bug in the API that we are consuming that is causing this error.

**Comment by KrisGraySFDC** [comment]
Work item: @W-6723813

**Comment by mysticflute** [comment]
this is now fixed in `1.0.6`

**Comment by RupertBarrow** [comment]
Great !

**Comment by JimmyBarzmark** [comment]
I am seeing this error now as well. This worked yesterday and now the local Salesforce server does not compile and run.
sfdx force:lightning:lwc:start

**Process halts with:**
Use of this plugin is subject to the Salesforce.com Program Agreement. 
By installing this plugin, you agree to the Salesforce.com Program Agreement<https://trailblazer.me/terms> 
and acknowledge the Salesforce Privacy Policy<https://www.salesforce.com/company/privacy.jsp>.
*****************************************************
$ Sfdx force:org:list --all
I am authenticated and the org is connected
