### ISSUE TITLE
lightning/breadcrumbs  is imported but could not be resolved

### ISSUE THREAD

**Issue by Tzeimi** [forcedotcom/lwc-dev-server-feedback#48]
Hello,

Today I wanted to develop new lwc on local environment but started to get this issues when starting the server

[0] [rollup] 'lightning/breadcrumbs' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/preview/preview.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/breadcrumb' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/preview/preview.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/spinner' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/preview/preview.html, but could not be resolved – treating it as an external dependency

Error: Error compiling force/lds
    at Proxy.compile (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/compiler/compiler.js:231:15)
Caused by: Error: Could not resolve entry (force/lds)
    at error (/Users/myUser/.local/share/sfdx/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/myUser/.local/share/sfdx/node_modules/rollup/dist/rollup.js:21359:17
    at async Promise.all (index 0)
    at async Proxy.compile (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/compiler/compiler.js:202:24)
    at async Promise.all (index 0)
    at async FileSystemResourceProvider.get (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/resources/filesystem-resource-provider.js:49:32)
    at async webruntimeResources (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/server/resource-middleware.js:37:36)
[view__mainLayout.js] Done in 44 ms
0] [rollup] 'lightning/verticalNavigation' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/componentsPanel/componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/verticalNavigationSection' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/componentsPanel/componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/verticalNavigationItemIcon' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/componentsPanel/componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/icon' is imported by ../../.local/share/sfdx/node_modules/@salesforce/lwc-dev-server/modules/localdevserver/resourcesPanel/resourcesPanel.html, but could not be resolved – treating it as an external dependency

[view__home.js] Done in 1367 ms
Writing /Users/myUser/dev/sfdc_retail_metadata/.localdevserver/public/webruntime/view/eaf2cb0c78/dev/en_US/home.js...
[lds] Done in 18 ms
Error: Error compiling force/lds
    at Proxy.compile (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/compiler/compiler.js:231:15)
Caused by: Error: Could not resolve entry (force/lds)
    at error (/Users/myUser/.local/share/sfdx/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/myUser/.local/share/sfdx/node_modules/rollup/dist/rollup.js:21359:17
    at async Promise.all (index 0)
    at async Proxy.compile (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/compiler/compiler.js:202:24)
    at async Promise.all (index 0)
    at async FileSystemResourceProvider.get (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/resources/filesystem-resource-provider.js:49:32)
    at async webruntimeResources (/Users/myUser/.local/share/sfdx/node_modules/@webruntime/compiler/dist/commonjs/server/resource-middleware.js:37:36)
[lds] Done in 3 ms

So I wasnt able to see any of the lwc,

working environment:

OSX Catalina 10.15.2
node: 13.1.0
npm: 6.13.1

any thoughts?

**Comment by Triopticon** [comment]
This look like it is related to the "Bad Request" issue (aggregate-ui issue): #1  and Local dev server error with API version 48 #47 .

The same lines are in the output for error reported in #47 .

@Tzeimi, can you confirm you are connecting to a Spring 20 (API 48) sandbox?

**Comment by Tzeimi** [comment]
Yes, Im using  a Spring 20 sandbox

**Comment by RalfMa** [comment]
Same issue here.

**Comment by KrisGraySFDC** [comment]
We are adding API Version 48 support to local dev right now. Eta is 1-3 business days. 

Thank you for reporting it.

**Comment by jastend** [comment]
That's great to hear. Thank you very much!

**Comment by KrisGraySFDC** [comment]
We have patched local dev to give initial support for version 48. More changes are likely coming next week, but for now our hope is you are unblocked.

Be sure to update
`sfdx update`


If you're still having issues, please let us know so we can investigate for our follow up improvements.

**Comment by tosunilgupta** [comment]
> up impr

Still this is not working for my local environment. 

`Server up on http://localhost:3333
Resolved 21 LWC modules in 23261 ms
[0] [rollup] 'lightning/breadcrumbs' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\preview\preview.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/spinner' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\preview\preview.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/breadcrumb' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\preview\preview.html, but could not be resolved
– treating it as an external dependency
[view__preview.js] Done in 71080 ms
Writing d:\Users\myUser\Documents\GitHub\blocx-dev-lwc-v1.0.0-r1\.localdevserver/public/webruntime/view/8317de4485/dev/en_US/preview.js...
[view__mainLayout.js] Done in 229 ms
Writing d:\Users\myUser\Documents\GitHub\blocx-dev-lwc-v1.0.0-r1\.localdevserver/public/webruntime/view/67133358b1/dev/en_US/mainLayout.js...
[lds] Done in 1515 ms
Error: Error compiling force/lds
    at Proxy.compile (C:\Users\sgupta23\AppData\Local\sfdx\node_modules\@webruntime\compiler\dist\commonjs\compiler\compiler.js:231:15)
Caused by: Error: Could not resolve entry (force/lds)
    at error (C:\Users\myUser\AppData\Local\sfdx\node_modules\rollup\dist\rollup.js:3460:30)
    at C:\Users\sgupta23\AppData\Local\sfdx\node_modules\rollup\dist\rollup.js:21359:17
[0] [rollup] 'lightning/verticalNavigationItemIcon' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\componentsPanel\componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/verticalNavigation' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\componentsPanel\componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/verticalNavigationSection' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\componentsPanel\componentsPanel.html, but could not be resolved – treating it as an external dependency
[0] [rollup] 'lightning/icon' is imported by C:\Users\myUser\AppData\Local\sfdx\node_modules\@salesforce\lwc-dev-server\modules\localdevserver\resourcesPanel\resourcesPanel.html, but could not be resolved – treating it as an external dependency
[view__home.js] Done in 1713 ms
Writing d:\Users\myUser\Documents\GitHub\blocx-dev-lwc-v1.0.0-r1\.localdevserver/public/webruntime/view/eaf2cb0c78/dev/en_US/home.js...`

**Comment by jastend** [comment]
Issue has been resolved for me. My versions are:

```
> sfdx version
sfdx-cli/7.36.0-b1c4e9c7c8 win32-x64 node-v10.15.3
> sfdx plugins
@salesforce/lwc-dev-server 1.0.10
├─ @oclif/plugin-help 2.2.3
└─ @oclif/plugin-update 1.3.9
```

**Comment by tosunilgupta** [comment]
(Hooray) Finally we performed some steps and my local is working as expected.

**Step 1:**: Please update the local sfdx version
`sfdx update`

**Step 2:**: To update the sfdx local server, please install the plugin as per  below command.
`sfdx plugins:install @salesforce/lwc-dev-server`

**Step 3:**: Re-validate local sfdx environment version.
`sfdx plugins --core`

**Step 4:**: Run the local server.
`sfdx force:lightning:lwc:start`

Above mentioned steps will help us to established the local environment up again as per expectation.
