### ISSUE TITLE
Local dev server throws error `Unable to expose method "then"` on startup

### ISSUE THREAD

**Issue by navratilpavel** [forcedotcom/lwc-dev-server-feedback#71]
**Describe the bug**
On startup the plugin throws this error:

`Error: Unable to expose method "then"
    at Object.plumbing.exposePromiseMethod (~/.local/share/sfdx/node_modules/jsdom/node_modules/request-promise-core/lib/plumbing.js:140:19)
    at module.exports (~/.local/share/sfdx/node_modules/jsdom/node_modules/request-promise-core/configure/request2.js:57:83)
    at Object.<anonymous> (~/.local/share/sfdx/node_modules/jsdom/node_modules/request-promise-native/lib/rp.js:15:1)
    at Module._compile (~/.local/share/sfdx/client/7.62.1-309fe6da17/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at LazyLoader.loadModule (~/.local/share/sfdx/client/7.62.1-309fe6da17/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:139:21)
    at Function._load (~/.local/share/sfdx/client/7.62.1-309fe6da17/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:115:29)`

**To Reproduce**
1. Run sfdx force:lightning:lwc:start
2. Error occurs

**Expected behavior**
It should start. ;-)

**Desktop:**
 - OS: macOS Catalina

**Additional context**
List of DX plugins that are installed.

`sfdx plugins
@oclif/plugin-autocomplete 0.2.0
@salesforce/lwc-dev-mobile 0.2.1
@salesforce/lwc-dev-server 2.1.1
├─ @oclif/plugin-update 1.3.9
└─ @oclif/plugin-help 2.2.1

@salesforce/sfdx-diff 0.0.6
salesforcedx 48.18.1
├─ @salesforce/sfdx-plugin-lwc-test 0.1.5
├─ custom-metadata 1.0.0
├─ salesforcedx-templates 48.18.0
└─ salesforce-alm 48.19.0`

**Comment by navratilpavel** [comment]
The issue is the same as this one:
https://github.com/forcedotcom/lwc-dev-server-feedback/issues/37

**Comment by lcampos** [comment]
Thanks for opening this issue @navratilpavel . Can you explain why this is a duplicate of #37 ? Can you provide an example of the configuration you are using in your project so we can replicate the issue on our side ?

**Comment by navratilpavel** [comment]
@lcampos sorry, was a https://github.com/forcedotcom/lwc-dev-server-feedback/issues/57 ... my fault ... inside of https://github.com/forcedotcom/lwc-dev-server-feedback/issues/57 is a comment from @pbattisson ... he has a similar issue as me ... so the issue was not solved yet

**Comment by navratilpavel** [comment]
@lcampos for creating of DX project I'm using [Illuminated Cloud](http://www.illuminatedcloud.com/). 

package.json
`{
  "name": "salesforce-app",
  "private": true,
  "version": "1.0.0",
  "description": "Salesforce App",
  "scripts": {
    "lint": "npm run lint:lwc",
    "lint:lwc": "eslint force-app/main/default/lwc",
    "test": "npm run test:unit",
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "test:unit:coverage": "sfdx-lwc-jest --coverage",
    "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
    "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\""
  },
  "devDependencies": {
    "@prettier/plugin-xml": "^0.7.0",
    "@salesforce/eslint-config-lwc": "^0.4.0",
    "@salesforce/sfdx-lwc-jest": "^0.7.0",
    "eslint": "^5.16.0",
    "prettier": "^1.19.1",
    "prettier-plugin-apex": "^1.0.0"
  }
}
`

sfdx-project.json
`{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "48.0"
}`
