### ISSUE TITLE
Got error while installing

### ISSUE THREAD

**Issue by k010c1232** [forcedotcom/lwc-dev-server-feedback#75]
**Describe the bug**
I got the following error while installing @salesforce/lwc-dev-server.

```txt
➜  ~ sfdx plugins:install @salesforce/lwc-dev-server
Successfully validated digital signature for @salesforce/lwc-dev-server.
Finished digital signature check.
warning @salesforce/lwc-dev-server > cpx > chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @salesforce/lwc-dev-server > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @salesforce/lwc-dev-server > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning @salesforce/lwc-dev-server > cpx > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @salesforce/lwc-dev-server > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @salesforce/lwc-dev-server > @salesforce/core > jsforce > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
warning @salesforce/lwc-dev-server > @webruntime/api > @lwc/compiler > rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-node-resolve@4.2.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
warning @salesforce/lwc-dev-server > @webruntime/compiler > rollup-plugin-commonjs@9.3.4: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
warning @salesforce/lwc-dev-server > cpx > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @salesforce/lwc-dev-server > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning @salesforce/lwc-dev-server > cpx > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @salesforce/lwc-dev-server > cpx > chokidar > readdirp > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning "@salesforce/lwc-dev-server > @rollup/plugin-alias@3.1.1" has unmet peer dependency "rollup@^1.20.0||^2.0.0".
warning "@salesforce/lwc-dev-server > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
warning "@salesforce/lwc-dev-server > request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
warning Error running install script for optional dependency: "/Users/win/.local/share/sfdx/node_modules/cpx/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/win/.local/share/sfdx/node_modules/cpx/node_modules/fsevents
Output:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}"
Installing plugin @salesforce/lwc-dev-server... installed v2.5.1
```

**To Reproduce**
1. Type 'sfdx plugins:install @salesforce/lwc-dev-server'

**Desktop (please complete the following information):**
 - OS: [Mac]
 - OS Version [10.15.6 (19G2021)]
 - Node Version [v14.2.0]
 - npm Version [6.14.8]

**Additional context**
Node was installed with anyenv.

**Comment by k010c1232** [comment]
Everything is fine after I installed node-gyp.
